# Generated by Django 5.0.6 on 2024-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_blocking_blocked_remove_blocking_blocker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friendship_status',
            new_name='status',
        ),
    ]
