# Generated by Django 5.0.6 on 2024-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_friendship_status_friendship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='friends_since',
            field=models.DateTimeField(null=True),
        ),
    ]
