# Generated by Django 5.0.6 on 2024-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_friendship_friends_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
