# Generated by Django 5.0.6 on 2024-05-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_last_action 2'),
        ('api', '0006_user_last_action'),
    ]

    operations = [
    ]
