FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip freeze > pip.txt

EXPOSE 8000

CMD ["python", "usermanagement/manage.py", "runserver", "0.0.0.0:8000"]


